version: "3.9"

services:
  backend:
    build: ./project
    container_name: backend
    working_dir: /app
    volumes:
      - ./project:/app
    ports:
      - "8000:8000"
    env_file:
      - ./project/.env
    command: >
      python -m uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - redis
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
