version: "3.8"
services:
  web:
    build: .
    contaioner_name: news_app
    environment:
      REDIS_HOST: my-redis
      REDIS_PORT: "6379"
    ports:
      - "8000:8000"
    command: >
      python -m uvicorn app:app
      --host 0.0.0.0
      --port 8000
      --reload
    network:
    - project_default

networks:
  project_default:
    external: true