services:
  my-redis:
    image: redis:7-alpine
    container_name: my-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - project_default

  web:
    build: .
    container_name: news_app
    volumes:
      - ./:/app
    working_dir: /app 
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    command: >
      python -m uvicorn app:app
      --host 0.0.0.0
      --port 8000
      --reload
    depends_on:
      - my-redis
    networks:
      - project_default

networks:
  project_default:
    external: true
